import json
import boto3
import uuid
import datetime


lex_client = boto3.client('lexv2-runtime')

def lambda_handler(event, context):
    """
    Accepts an event generated by API Gateway.
    Requests NLP from AWS Lex, and responds to user.
    """
    
    user_message = event['messages'][0]['unstructured']['text']
    
    lex_response = lex_client.recognize_text(
        botId='H5OHJKW4AD',
        botAliasId='4F2EPLLYN4',
        localeId='en_US',
        sessionId='123',
        text=user_message,
    )
    
    message = lex_response['messages'][0]['content']
    
    return {
      "messages": [
        {
          "type": "unstructured",
          "unstructured": {
            "id": "some-id",
            "text": message,
            "timestamp": datetime.datetime.now().isoformat(),
          }
        }
      ]
    }
